name: pylids
channels:
  - anaconda
  - conda-forge
  - omnia
dependencies:
  - python==3.7
  - numpy
  - scipy
  - matplotlib
  - opencv>=4.0.0
  - jupyter
  - ipython
  - pillow
  - tqdm
  - cython
  - numexpr
  - pip
  - pypng
  - tensorflow-gpu==1.15.0
  - cudatoolkit==10.0.130
  - pip:
    - appdirs
    - imagecorruptions
