all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
- - 27
- - 28
- - 29
- - 30
- - 31
all_joints_names:
- Lcorner
- Rcorner
- upper1
- upper2
- upper3
- upper4
- upper5
- upper6
- upper7
- upper8
- upper9
- upper10
- upper11
- upper12
- upper13
- upper14
- upper15
- lower1
- lower2
- lower3
- lower4
- lower5
- lower6
- lower7
- lower8
- lower9
- lower10
- lower11
- lower12
- lower13
- lower14
- lower15
alpha_r: 0.02
batch_size: 8
clahe: false
claheratio: 0.1
cropratio: 0.4
dataset: training-datasets/iteration-0/project_name/project_name.mat
dataset_type: default
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: false
histeqratio: 0.1
init_weights: /path/to/init/weights
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/project_name/Documentation_data-project_name.pickle
min_input_size: 64
mirror: false
multi_step:
- - 0.0001
  - 40000
- - 5e-05
  - 60000
- - 1e-05
  - 120000
net_type: resnet_50
num_joints: 32
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /path/to/dlc/project_folder/
rotation: 0
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
covering: false
elastic_transform: false
motion_blur: false
optimizer: adam
